server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Product Service
spring.cloud.gateway.server.webmvc.routes[0].id=product-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://product-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/products/**

# Order Service
spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/orders/**

# Load Balancer cache
spring.cloud.loadbalancer.cache.ttl=5s
spring.cloud.loadbalancer.cache.capacity=256

